cloud:
  aws:
    credentials:
      access-key: AKIA4DBVAN2K3R7MDBHH
      secret-key: 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
      instance-profile: false
server:
  port: 80
spring:
  data:
   mongodb:
    port: 27017
    host: localhost
    database: domino_jfl_db
    username: domino_jfl_user
    password: domino_jfl_pass
    authentication-database: domino_jfl_db

